<?php
/**
 * @file
 * An Appointment Slot entity type module.
 */

/**
 * Implements hook_entity_info().
 */
function appointment_slot_entity_info() {
  $entities = array();

  $entities['appointment_slot'] = array(
    'label' => t('Appointment Slot'),
    'entity class' => 'AppointmentSlotEntity',
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'access callback' => 'appointment_slot_access',
    'controller class' => 'AppointmentSlotController',
    'views controller class' => 'EntityDefaultViewsController',
    'base table' => 'appointment_slot',
    'entity keys' => array(
      'id' => 'slot_id',
      'label' => 'slot_id',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'static cache' => TRUE,
    'fieldable' => TRUE,
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => FALSE,
      ),
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => TRUE,
      ),
    ),
    'module' => 'appointment_slot',
    'view callback' => 'entity_metadata_view_single',
    'metatags' => FALSE,
    'redirect' => FALSE,
  );

  foreach (appointment_slot_types() as $name => $type) {
    $entities['appointment_slot']['bundles'][$name] = array(
      'label' => $type['label'],
      'admin' => array(
        'path' => 'admin/structure/appointments/slots/types/' . $name,
        'real path' => 'admin/structure/appointments/slots/types/' . $name,
        'bundle argument' => 5,
        'access arguments' => array('appointment slot: administer types'),
      ),
    );
  }

  return $entities;
}

/**
 * Implements hook_field_extra_fields().
 */
function appointment_slot_field_extra_fields() {
  $extra = array();
  foreach (array_keys(appointment_slot_types()) as $bundle) {
    $extra['appointment_slot'][$bundle]['display'] = array(
      'links' => array(
        'label' => t('Action links'),
        'weight' => -100,
      ),
    );
    $extra['appointment_slot'][$bundle]['form'] = array(
      'published' => array(
        'label' => t('Published status'),
        'weight' => 90,
      ),
    );
  }
  return $extra;
}

/**
 * Implements hook_menu().
 */
function appointment_slot_menu() {
  $items = array();
  $items['admin/structure/appointments/slots/add'] = array(
    'title' => 'Add new slot',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('appointment slot: add new'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/structure/appointments/slots/types'] = array(
    'title' => 'Appointment slot types',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('appointment slot: administer types'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  foreach (appointment_slot_types() as $name => $type) {
    $items['admin/structure/appointments/slots/add/' . $name] = array(
      'title callback' => 'appointment_slot_add_title',
      'title arguments' => array($name),
      'description' => !empty($type['description']) ? $type['description'] : '',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('appointment_slot_form', $name),
      'access arguments' => array('appointment slot: add new'),
      'file' => 'includes/appointment_slot.forms.inc',
    );
  }
  $items['appointments/slots/%appointment_slot'] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('appointment_slot', 2),
    'page callback' => 'appointment_slot_view',
    'page arguments' => array(2, 'full'),
    'access callback' => 'appointment_slot_access',
    'access arguments' => array('view', 2),
  );
  $items['appointments/slots/%appointment_slot/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['appointments/slots/%appointment_slot/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('appointment_slot_form', 2),
    'access callback' => 'appointment_slot_access',
    'access arguments' => array('update', 2),
    'file' => 'includes/appointment_slot.forms.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => 1,
  );
  $items['appointments/slots/%appointment_slot/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('appointment_slot_delete_confirm', 2),
    'access callback' => 'appointment_slot_access',
    'access arguments' => array('delete', 2),
    'file' => 'includes/appointment_slot.forms.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 2,
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function appointment_slot_admin_paths() {
  return array(
    'appointments/slots/*/edit' => TRUE,
    'appointments/slots/*/delete' => TRUE,
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function appointment_slot_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'admin/structure/appointments/slots' || $root_path == 'appointments') {
    foreach (appointment_slot_types() as $name => $types) {
      $item = menu_get_item('admin/structure/appointments/slots/add/' . $name);
      if ($item['access']) {
        $item['localized_options']['query']['destination'] = $root_path;
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
    }
  }
}

/**
 * Access callback for appointment slots.
 *
 * @param string $op
 *   The operation to check access for ('view', 'delete', or 'update').
 * @param AppointmentSlotEntity $slot
 *   The slot entity.
 * @param object $account
 *   The Drupal user account (defaults to the current user).
 *
 * @return bool
 *   TRUE or FALSE for whether access is granted.
 */
function appointment_slot_access($op, AppointmentSlotEntity $slot, $account = NULL) {
  $account = $account ? $account : $GLOBALS['user'];
  $own = $account->uid && $slot->uid == $account->uid;
  switch ($op) {
    case 'view':
      if ($own) {
        return TRUE;
      }
      elseif (user_access('appointment slot: update any', $account)) {
        return TRUE;
      }
      elseif ($slot->published && user_access('appointment slot: view published', $account)) {
        return TRUE;
      }
      return FALSE;

    case 'update':
    case 'delete':
      if ($own && user_access('appointment slot: update own', $account)) {
        return TRUE;
      }
      elseif (user_access('appointment slot: update any', $account)) {
        return TRUE;
      }
      return FALSE;

  }
  return FALSE;
}

/**
 * Menu title callback for adding a new slot.
 *
 * @param string $name
 *   The machine name for the slot type.
 *
 * @return string
 *   A menu or page title.
 */
function appointment_slot_add_title($name) {
  if ($name == 'default') {
    return t('Add new slot');
  }
  $type = appointment_slot_type_load($name);
  return t('Add new slot (@type)', array('@type' => $type['label']));
}

/**
 * Get a list of options for the 'published' database column.
 *
 * @return array
 */
function appointment_slot_published_options() {
  return array(0 => t('Unpublished'), 1 => t('Published'));
}

/**
 * Implements hook_permission().
 */
function appointment_slot_permission() {
  return array(
    'appointment slot: administer types' => array(
      'title' => t('Administer appointment slot types'),
    ),
    'appointment slot: add new' => array(
      'title' => t('Create appointment slots'),
    ),
    'appointment slot: update any' => array(
      'title' => t('Update any appointment slots'),
    ),
    'appointment slot: update own' => array(
      'title' => t('Update own appointment slots'),
    ),
    'appointment slot: view published' => array(
      'title' => t('View published appointment slots'),
    ),
  );
}

/**
 * Load an appointment slot type by its machine name.
 *
 * @param string $name
 *   The machine name of the slot type.
 *
 * @return object
 *   An appointment slot type object, or FALSE if the type cannot be found.
 */
function appointment_slot_type_load($name = 'default') {
  $types = appointment_slot_types();
  if (isset($types[$name])) {
    return $types[$name];
  }
  return FALSE;
}

/**
 * View an appointment slot.
 *
 * @param AppointmentSlotEntity $slot
 * @param string $view_mode
 *
 * @return array
 *   A Drupal render array.
 */
function appointment_slot_view(AppointmentSlotEntity $slot, $view_mode = 'full') {
  $build = array();

  $build['links'] = array(
    '#theme' => 'links',
    '#attributes' => array('class' => 'appointment-slot-links'),
  );

  if ($view_mode != 'full') {
    $build['links']['#links']['more'] = array(
      'title' => t('More details'),
      'href' => 'appointments/slots/' . $slot->slot_id,
    );
  }

  field_attach_prepare_view('appointment_slot', array($slot->slot_id => $slot), $view_mode);
  entity_prepare_view('appointment_slot', array($slot->slot_id => $slot));
  $build += field_attach_view('appointment_slot', $slot, $view_mode);

  $build += array(
    '#theme' => 'appointment_slot',
    '#slot' => $slot,
    '#view_mode' => $view_mode,
  );

  if (!empty($slot->slot_id) && $view_mode == 'teaser') {
    $build['#contextual_links']['appointment_slot'] = array('appointment-slot', array($slot->slot_id));
  }

  // Invoke hook_entity_view().
  global $language;
  $langcode = $language->language;
  module_invoke_all('entity_view', $slot, 'appointment_slot', $view_mode, $langcode);

  // Invoke hook_ENTITY_TYPE_view_alter() and hook_entity_view_alter().
  $type = 'appointment_slot';
  drupal_alter(array('appointment_slot_view', 'entity_view'), $build, $type);

  return $build;
}

/**
 * Implements hook_theme().
 */
function appointment_slot_theme() {
  return array(
    'appointment_slot' => array(
      'render element' => 'elements',
      'template' => 'includes/appointment-slot',
      'file' => 'includes/appointment_slot.theme.inc',
    ),
  );
}

/**
 * Load an appointment slot.
 *
 * @param int $slot_id
 *
 * @return AppointmentSlotEntity|FALSE
 *   The slot entity, or FALSE if it cannot be found.
 */
function appointment_slot_load($slot_id) {
  $slots = appointment_slot_load_multiple(array($slot_id));
  return $slots ? reset($slots) : FALSE;
}

/**
 * Load multiple appointment slots.
 *
 * @param array $slot_ids
 * @param array $conditions
 * @param bool $reset
 *
 * @return AppointmentSlotEntity[]
 *   An array of appointment slot entities, keyed by the entity ID.
 */
function appointment_slot_load_multiple(array $slot_ids = array(), array $conditions = array(), $reset = FALSE) {
  return entity_load('appointment_slot', $slot_ids, $conditions, $reset);
}

/**
 * Get a list of slot types.
 *
 * @return array
 *   An array of types.
 */
function appointment_slot_types() {
  $types = array(
    'default' => array(
      'label' => t('Default'),
      'description' => t('A default slot type.'),
      'module' => 'appointment_slot',
    ),
  );
  drupal_alter(__FUNCTION__, $types);
  return $types;
}

/**
 * Implements hook_views_api().
 */
function appointment_slot_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'appointment_slot') . '/includes',
  );
}
