<?php
/**
 * @file
 * Appointments Booking module.
 */

/**
 * Get a list of booking statuses.
 *
 * @return array
 *   An array of booking statuses: the keys are machine names and the values are
 *   human-readable labels.
 */
function appointments_booking_status_options() {
  return array(
    'draft' => t('Draft'),
    'pending' => t('Pending'),
    'booked' => t('Booked'),
    'canceled' => t('Canceled'),
  );
}
